version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    volumes:
      - ./db_conf:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  api:
    container_name: api
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    logging:
      driver: none