version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    ports:
      - "5432:5432"
    env_file:
      - .env
  api:
    container_name: api
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    logging:
      driver: none
  rabbit:
    container_name: rabbit_mq
    hostname: rabbit
    image: rabbitmq:3.11.0
    ports:
      - "5672:5672"
    env_file:
      - .env
    logging:
      driver: none
  celery:
    container_name: celery
    build:
      context: celery_app/
      dockerfile: Dockerfile
    depends_on:
      - rabbit
    env_file:
      - .env
    volumes:
      - ./celery_app:/app
