"""Update user_group header attrs

Revision ID: a9e5ec83e114
Revises: f6d08d6b4888
Create Date: 2022-10-03 00:01:59.282682

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a9e5ec83e114'
down_revision = 'f6d08d6b4888'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
